# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas scikit-learn numpy

      - name: Run Python Script
        run: |
          python fetch_data.py

      - name: Commit and push predictions.csv
        env: 
          GH_PAT: ${{ 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 }}
        run: |
          git config --global user.email "leolin900114@gmail.com"
          git config --global user.name "leolin-hub"
          git add predictions.csv
          git commit -m "Add predictions.csv"
          git push https://leolin-hub:${GH_PAT}@github.com/leolin-hub/TestCICD.git
